# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  BINARY_NAME: BINARY_NAME
  MAIN_PKG: .

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build the binary
    cmds:
      - go build -o bin/{{.BINARY_NAME}} {{.MAIN_PKG}}

  test:
    desc: Run tests with race detection and coverage
    cmds:
      - go test -race -cover ./...

  lint:
    desc: Run linters
    cmds:
      - yamllint -c .yamllint.yaml .
      - golangci-lint run

  format:
    desc: Format code
    cmds:
      - go mod tidy
      - goimports -w .
      - go fmt ./...

  dev:
    desc: Format, lint, and test (development cycle)
    cmds:
      - task: format
      - task: lint
      - task: test

  ci:
    desc: Run full CI checks (format, lint, test, build)
    cmds:
      - task: format
      - task: lint
      - task: test
      - task: build

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf bin/ coverage.*
