# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  BINARY_NAME: go-template
  MAIN_PKG: .

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build the binary
    cmds:
      - go build -o bin/{{.BINARY_NAME}} {{.MAIN_PKG}}

  install:
    desc: Install the binary to $GOBIN
    vars:
      GIT_VERSION:
        sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
      GIT_COMMIT:
        sh: git rev-parse --short HEAD 2>/dev/null || echo "none"
      BUILD_DATE:
        sh: date -u +"%Y-%m-%dT%H:%M:%SZ"
    cmds:
      - go clean -i {{.MAIN_PKG}}
      - |
        go install -trimpath -v \
          -ldflags="-X main.version={{.GIT_VERSION}} -X main.commit={{.GIT_COMMIT}} -X main.date={{.BUILD_DATE}}" \
          {{.MAIN_PKG}}

  test:
    desc: Run tests with race detection and coverage
    cmds:
      - go test -race -cover ./...

  lint:
    desc: Run linters
    cmds:
      - yamllint -c .yamllint.yaml .
      - golangci-lint run

  format:
    desc: Format code
    cmds:
      - go mod tidy
      - goimports -w .
      - go fmt ./...

  dev:
    desc: Format, lint, and test (development cycle)
    cmds:
      - task: format
      - task: lint
      - task: test

  ci:
    desc: Run full CI checks (format, lint, test, build)
    cmds:
      - task: format
      - task: lint
      - task: test
      - task: build

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf bin/ coverage.*
